### ISSUE TITLE
issue in adding new lerner

### ISSUE THREAD

**Issue by jacksonsimethy2023** [akshay3kumar/HJJS_SWIM#1]
Exception in thread "main" java.lang.NumberFormatException: For input string: "1713705539974"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at UniqueIdGenerator.UniqueIdGenerator.generateUniqueId(UniqueIdGenerator.java:19)
	at HJSSSoftware.main(HJSSSoftware.java:142)
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)

**Comment by akshay3kumar** [comment]
fixed commit id : ca9aece6f38b0fd91ab87d90f053ffff2ccbb744
